// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fnf_modbitmap.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "fnf_modbitmap.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace FNF {

namespace {

const ::google::protobuf::Descriptor* mod_bitmap_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  mod_bitmap_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* EM_PLAT_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_fnf_5fmodbitmap_2eproto() {
  protobuf_AddDesc_fnf_5fmodbitmap_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "fnf_modbitmap.proto");
  GOOGLE_CHECK(file != NULL);
  mod_bitmap_descriptor_ = file->message_type(0);
  static const int mod_bitmap_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mod_bitmap, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mod_bitmap, plat_),
  };
  mod_bitmap_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      mod_bitmap_descriptor_,
      mod_bitmap::default_instance_,
      mod_bitmap_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mod_bitmap, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mod_bitmap, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(mod_bitmap));
  EM_PLAT_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_fnf_5fmodbitmap_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    mod_bitmap_descriptor_, &mod_bitmap::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_fnf_5fmodbitmap_2eproto() {
  delete mod_bitmap::default_instance_;
  delete mod_bitmap_reflection_;
}

void protobuf_AddDesc_fnf_5fmodbitmap_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023fnf_modbitmap.proto\022\003FNF\"5\n\nmod_bitmap"
    "\022\013\n\003uid\030\001 \002(\003\022\032\n\004plat\030\002 \002(\0162\014.FNF.EM_PLA"
    "T*%\n\007EM_PLAT\022\014\n\010PLAT_AND\020\001\022\014\n\010PLAT_IOS\020\002", 120);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fnf_modbitmap.proto", &protobuf_RegisterTypes);
  mod_bitmap::default_instance_ = new mod_bitmap();
  mod_bitmap::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_fnf_5fmodbitmap_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_fnf_5fmodbitmap_2eproto {
  StaticDescriptorInitializer_fnf_5fmodbitmap_2eproto() {
    protobuf_AddDesc_fnf_5fmodbitmap_2eproto();
  }
} static_descriptor_initializer_fnf_5fmodbitmap_2eproto_;
const ::google::protobuf::EnumDescriptor* EM_PLAT_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EM_PLAT_descriptor_;
}
bool EM_PLAT_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int mod_bitmap::kUidFieldNumber;
const int mod_bitmap::kPlatFieldNumber;
#endif  // !_MSC_VER

mod_bitmap::mod_bitmap()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void mod_bitmap::InitAsDefaultInstance() {
}

mod_bitmap::mod_bitmap(const mod_bitmap& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void mod_bitmap::SharedCtor() {
  _cached_size_ = 0;
  uid_ = GOOGLE_LONGLONG(0);
  plat_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

mod_bitmap::~mod_bitmap() {
  SharedDtor();
}

void mod_bitmap::SharedDtor() {
  if (this != default_instance_) {
  }
}

void mod_bitmap::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* mod_bitmap::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return mod_bitmap_descriptor_;
}

const mod_bitmap& mod_bitmap::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_fnf_5fmodbitmap_2eproto();
  return *default_instance_;
}

mod_bitmap* mod_bitmap::default_instance_ = NULL;

mod_bitmap* mod_bitmap::New() const {
  return new mod_bitmap;
}

void mod_bitmap::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    uid_ = GOOGLE_LONGLONG(0);
    plat_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool mod_bitmap::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 uid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_plat;
        break;
      }

      // required .FNF.EM_PLAT plat = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_plat:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::FNF::EM_PLAT_IsValid(value)) {
            set_plat(static_cast< ::FNF::EM_PLAT >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void mod_bitmap::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 uid = 1;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->uid(), output);
  }

  // required .FNF.EM_PLAT plat = 2;
  if (has_plat()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->plat(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* mod_bitmap::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 uid = 1;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->uid(), target);
  }

  // required .FNF.EM_PLAT plat = 2;
  if (has_plat()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->plat(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int mod_bitmap::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 uid = 1;
    if (has_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->uid());
    }

    // required .FNF.EM_PLAT plat = 2;
    if (has_plat()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->plat());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void mod_bitmap::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const mod_bitmap* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const mod_bitmap*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void mod_bitmap::MergeFrom(const mod_bitmap& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_plat()) {
      set_plat(from.plat());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void mod_bitmap::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mod_bitmap::CopyFrom(const mod_bitmap& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mod_bitmap::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void mod_bitmap::Swap(mod_bitmap* other) {
  if (other != this) {
    std::swap(uid_, other->uid_);
    std::swap(plat_, other->plat_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata mod_bitmap::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = mod_bitmap_descriptor_;
  metadata.reflection = mod_bitmap_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace FNF

// @@protoc_insertion_point(global_scope)
